language: haskell
sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - happy-1.19.4
      - alex-3.1.3
      - ghc-7.10.2
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - ghc --version
  - stack --version

script:
  - stack setup --system-ghc
  - stack build --system-ghc --no-terminal
  - stack test  --system-ghc --test-arguments --plain

cache:
  directories:
  - $HOME/.stack

